/** Auto-generated by `npm run paintings` — do not edit by hand. */
export const homeDrawings = [
  {
    "src": "/paintings/home/neural-net.jpg",
    "label": "Neural net",
    "slug": "neural-net"
  },
  {
    "src": "/paintings/home/transformer.jpg",
    "label": "Transformer",
    "slug": "transformer"
  },
  {
    "src": "/paintings/home/circuit.jpg",
    "label": "Circuit",
    "slug": "circuit"
  },
  {
    "src": "/paintings/home/chip.jpg",
    "label": "Chip",
    "slug": "chip"
  },
  {
    "src": "/paintings/home/rag-pipeline.jpg",
    "label": "RAG pipeline",
    "slug": "rag-pipeline"
  },
  {
    "src": "/paintings/home/gpu-grid.jpg",
    "label": "GPU grid",
    "slug": "gpu-grid"
  }
] as const;
